=== DonaldCen/HttpSimulateGate/src/test/resources/response-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT response-config (
        responses+)
>
<!ELEMENT responses (response)>
<!ELEMENT response (headers?,cookies?)>
<!ATTLIST response
        name ID #REQUIRED
        response-clazz CDATA #REQUIRED
        description CDATA #IMPLIED
        charset CDATA #IMPLIED
>
<!ELEMENT headers (header+)>
<!ELEMENT header EMPTY>
<!ATTLIST header
        name CDATA #REQUIRED
        value CDATA #REQUIRED
>
<!ELEMENT cookies (cookie+)>
<!ELEMENT cookie EMPTY>
<!ATTLIST cookie
        name CDATA #REQUIRED
        value CDATA #REQUIRED
>

=== DonaldCen/HttpSimulateGate/src/test/resources/response-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE response-config SYSTEM "response-config.dtd">
<response-config>
    <!-- 一个 responses 只能有一个response,且name 需要唯一,非数字开头，非空-->
    <responses>
        <response name="test1" response-clazz="com.xuanwu.ump.HttpSimulateGate.entity.ResponseResult">
            <headers>
                <header name="content-type" value="application/xml"/>
            </headers>
            <cookies>
                <cookie name="te" value="223"/>
                <cookie name="te" value="223"/>
            </cookies>
        </response>
    </responses>
    <responses>
        <response name="test2" response-clazz="com.xuanwu.ump.HttpSimulateGate.entity.ResponseResult">
            <headers>
                <header name="content-type" value="application/xml"/>
            </headers>
            <cookies>
                <cookie name="te" value="11"/>
            </cookies>
        </response>
    </responses>

</response-config>
